import PageTransition from '../components/PageTransition';
import PageHeader from '../components/PageHeader';
import { motion } from 'motion/react';
import { Settings, Cpu, ShieldCheck, HardHat, Zap, Activity } from 'lucide-react';

const technologies = [
  { icon: Settings, title: 'Gearless Synchronous Motors', desc: 'Permanent magnet synchronous motors (PMSM) that offer a smoother, quieter ride while significantly reducing energy consumption compared to traditional geared systems.' },
  { icon: Cpu, title: 'Smart IoT Monitoring', desc: 'Real-time data analytics and predictive maintenance. Our elevators self-diagnose and alert our service teams before a breakdown occurs.' },
  { icon: ShieldCheck, title: 'Multi-Redundant Safety', desc: 'Advanced electronic safety systems including overspeed governors, progressive safety gear, and automated rescue devices (ARD) for power failures.' },
  { icon: Zap, title: 'Regenerative Drives', desc: 'Eco-friendly drives that capture the energy generated by the elevator during braking and feed it back into the building\'s power grid.' },
  { icon: Activity, title: 'Destination Dispatch', desc: 'Intelligent traffic management systems that group passengers by destination, reducing wait times and improving overall building efficiency.' },
  { icon: HardHat, title: 'Seismic & Fire Protection', desc: 'Engineered to withstand seismic activity and equipped with fire emergency return operations to ensure passenger safety during critical events.' },
];

export default function Technology() {
  return (
    <PageTransition>
      <PageHeader 
        title="Technology & Safety" 
        subtitle="Innovation at the Core" 
        image="https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=1920&auto=format&fit=crop"
      />
      
      <section className="py-32 bg-stellar-charcoal text-white">
        <div className="max-w-7xl mx-auto px-6 md:px-12">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-12">
            {technologies.map((tech, index) => (
              <motion.div
                key={tech.title}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1, duration: 0.6 }}
                className="group p-8 border border-white/10 hover:border-stellar-blue bg-black/20 hover:bg-black/40 transition-all duration-500"
              >
                <div className="w-16 h-16 rounded-full bg-stellar-blue/10 flex items-center justify-center text-stellar-blue group-hover:bg-stellar-blue group-hover:text-white transition-colors duration-500 mb-8">
                  <tech.icon size={32} />
                </div>
                <h3 className="font-display text-2xl font-bold mb-4">{tech.title}</h3>
                <p className="text-stellar-gray font-light leading-relaxed">
                  {tech.desc}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>
    </PageTransition>
  );
}
